
namespace Sakura.Tools
{
	public enum ToolKind : ushort
	{
		None = 0,

		Diamond = 1,
		Separator = 2,

		File_New = 100,
		File_Open,
		File_Save,
		File_Print,
		File_Export,
		File_Import,
		File_Category = 100,

		Camera_Zoom = 200,
		Camera_ZoomIn,
		Camera_ZoomOut,
		Camera_Zoom100,
		Camera_ZoomFit,
		Camera_Pan,
		Camera_Rotate,
		Camera_ToggleRuler,
		Camera_ToggleScrollbar,
		Camera_ToggleGrid,
		Camera_ToggleGridSnap,
		Camera_RenderWireframe,
		Camera_RenderRough,
		Camera_RenderFinal,
		Camera_Category = 200,

		Edit_Paste = 300,
		Edit_Cut,
		Edit_Copy,
		Edit_Delete,
		Edit_Undo,
		Edit_Redo,
		Edit_Category = 300,

		Object_Select = 400,
		Object_Lasso,
		Object_Duplicate,
		Object_Warp,
		Object_Forward,
		Object_Back,
		Object_InFrontOf,
		Object_Behind,
		Object_ToFront,
		Object_ToBack,
		Object_Group,
		Object_Ungroup,
		Object_Clip,
		Object_Unclip,
		Object_CreateClipper,
		Object_DeleteClipper,
		Object_AlignLeft,
		Object_AlignHCenter,
		Object_AlignRight,
		Object_AlignTop,
		Object_AlignVCenter,
		Object_AlignBottom,
		Object_Category = 400,

		Node_Select = 500,
		Node_Eraser,
		Node_Crop,
		Node_Knife,
		Node_ContinueCurve,
		Node_MergeNodes,
		Node_DiceCurve,
		Node_SliceCurve,
		Node_SliceCurveAndTrim,
		Node_Cusp,
		Node_Smooth,
		Node_Symmetric,
		Node_ToCurve,
		Node_ToLine,
		Node_AllCusp,
		Node_AllSmooth,
		Node_AllSymmetric,
		Node_AllToCurve,
		Node_AllToLine,
		Node_Combine,
		Node_Separate,
		Node_ObjectToCurves,
		Node_Union,
		Node_Intersect,
		Node_SubtractFront,
		Node_SubtractBack,
		Node_Xor,
		Node_Boundary,
		Node_Category = 500,

		Draw_Freehand = 600,
		Draw_Brush,
		Draw_Curve,
		Draw_Rectangle,
		Draw_Ellipse,
		Draw_Polygon,
		Draw_Star,
		Draw_Category = 600,

		Style_Fill = 700,
		Style_Stroke,
		Style_Dropper,
		Style_Transparency,
		Style_StartArrow,
		Style_EndArrow,
		Style_Weight0,
		Style_Weight1,
		Style_Weight2,
		Style_Weight4,
		Style_Weight8,
		Style_Weight16,
		Style_Category = 700,

		Text_Tool = 800,
		Text_Paragraph,
		Text_LeftAlign,
		Text_RightAlign,
		Text_Center,
		Text_Justify,
		Text_JustifyAll,
		Text_Bold,
		Text_Italic,
		Text_Underline,
		Text_Strike,
		Text_Superscript,
		Text_Subscript,
		Text_Category = 800,
	}
}
